- hosts: web
  become: yes
  tasks:
    - name: Install Flask
      yum:
        name: python3-flask
        state: present

    - name: Upload app.py
      copy:
        src: app.py
        dest: /home/ec2-user/app.py

    - name: Run app
      shell: nohup python3 /home/ec2-user/app.py &
